In [1]:
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv('orders.csv')
date

           date  product_id  city_id  orders
0    2019-12-10        5628       25       3
1    2018-08-15        3646       14     157
2    2018-10-23        1859       25       1
3    2019-08-17        7292       25       1
4    2019-01-06        4344       25       3
..          ...         ...      ...     ...
995  2018-10-08         255       13       1
996  2018-12-06        5521        7       1
997  2019-05-07         487       26      14
998  2019-03-03        1503       21       2
999  2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [5]:
time = pd.read_csv('messages.csv')
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [8]:
date['date']= pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1. Extract year

In [10]:
date['date_year'] = date['date'].dt.year
date

          date  product_id  city_id  orders  date_year
0   2019-12-10        5628       25       3       2019
1   2018-08-15        3646       14     157       2018
2   2018-10-23        1859       25       1       2018
3   2019-08-17        7292       25       1       2019
4   2019-01-06        4344       25       3       2019
..         ...         ...      ...     ...        ...
995 2018-10-08         255       13       1       2018
996 2018-12-06        5521        7       1       2018
997 2019-05-07         487       26      14       2019
998 2019-03-03        1503       21       2       2019
999 2019-10-15        6371        7      22       2019

[1000 rows x 5 columns]

2. Extract month

In [13]:
date['date_month'] = date['date'].dt.month
date

          date  product_id  city_id  orders  date_year  date_month
0   2019-12-10        5628       25       3       2019          12
1   2018-08-15        3646       14     157       2018           8
2   2018-10-23        1859       25       1       2018          10
3   2019-08-17        7292       25       1       2019           8
4   2019-01-06        4344       25       3       2019           1
..         ...         ...      ...     ...        ...         ...
995 2018-10-08         255       13       1       2018          10
996 2018-12-06        5521        7       1       2018          12
997 2019-05-07         487       26      14       2019           5
998 2019-03-03        1503       21       2       2019           3
999 2019-10-15        6371        7      22       2019          10

[1000 rows x 6 columns]